### PR TITLE
Integrate Instabug

### PR DESCRIPTION
**Pull request by MalcolmMcFly**
**What's this do?**
Integrated Instabug into the project and revved core to include card creator updates

**Why are we doing this? (w/ JIRA link if applicable)**
[SIMPLY-2312: SA: Card creator](https://jira.nypl.org/browse/SIMPLY-2312)
No ticket for the Instabug changes, but we added Instabug to improve the changes of us getting feedback from beta testers.

**How should this be tested? / Do these changes have associated tests?**
1. Launch the application and add NYPL to accounts from Settings
2. Attempt to create a library card
Instabug: Simply run the build, shake your phone or hit the report a bug fab button.

**Dependencies for merging? Releasing to production?**
n/a

**Has the application documentation been updated for these changes?**
n/a

**Did someone actually run this code to verify it works?**
@MalcolmMcFly @io7m

### CODE REVIEW

**Comment by io7m** [comment]
To clarify, it's actually that we need to update `instabug.conf` in the `Certificates` repos, and add a line to the Travis CI build to copy that file in: https://github.com/NYPL-Simplified/Simplified-Android-SimplyE/blob/develop/.travis-pre.sh#L63

Core doesn't know anything about Instabug, really.

**Comment by MalcolmMcFly** [comment]
> To clarify, it's actually that we need to update `instabug.conf` in the `Certificates` repos, and add a line to the Travis CI build to copy that file in: https://github.com/NYPL-Simplified/Simplified-Android-SimplyE/blob/develop/.travis-pre.sh#L63
> 
> Core doesn't know anything about Instabug, really.

Good call out, just updated it.

**Review by twaddington — COMMENTED** [review]
Looks okay to me.

**Review by io7m — APPROVED** [review]
:tada:

**Pull request merged**
